# push contents of this repo to specified repo on github on commit
name: push this repo to bundle repo
on: [push]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: push to bundle repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SM_ACCESS_TOKEN }}
          branch: master
          force: true
          directory: .
          repository: ranchimall/dappbundle
