# push contents of this repo to specified repo on github on commit
name: push this repo to bundle repo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: push to bundle repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SM_ACCESS_TOKEN }}
          branch: master
          force: true
          directory: .
          repository: https://github.com/ranchimall/dappbundle.git
          target-directory: btcwallet
